const SUPABASE_URL='https://hlbfhfotkexjtzbpdqls.supabase.co'; const SUPABASE_KEY='sb_publishable_u_z7UIdFMSu1GKyD-Uqa7A_uL59vVWj';
const form = document.querySelector('#volunteer-form');
const signinButton = document.createElement('button'); signinButton.className='signin-trigger'; signinButton.type='button'; signinButton.textContent='Sign in'; document.querySelector('.nav-links').prepend(signinButton);
const signupButton = document.createElement('button'); signupButton.className='signup-trigger'; signupButton.type='button'; signupButton.textContent='Sign up'; document.querySelector('.nav-links').prepend(signupButton);
const modal = document.querySelector('#signin-modal');
signinButton.addEventListener('click', () => { modal.dataset.mode='login'; fullNameField.style.display='none'; phoneField.style.display='none'; modal.classList.add('show'); modal.setAttribute('aria-hidden','false'); modal.querySelector('input').focus(); });
signupButton.addEventListener('click', () => { modal.dataset.mode='signup'; fullNameField.style.display='flex'; phoneField.style.display='flex'; modal.classList.add('show'); modal.setAttribute('aria-hidden','false'); modal.querySelector('.modal-kicker').textContent='JOIN SOCH COMMUNITY'; modal.querySelector('h2').textContent='Create your account.'; modal.querySelector('.signin-status').textContent='Use your email and a password of at least 6 characters.'; fullNameField.querySelector('input').focus(); });
const fullNameField=document.createElement('label'); fullNameField.innerHTML='Full name<input name="fullName" placeholder="Your full name">'; const phoneField=document.createElement('label'); phoneField.innerHTML='Phone number<input name="phone" placeholder="03XX XXXXXXX">'; document.querySelector('#signin-form').prepend(phoneField); document.querySelector('#signin-form').prepend(fullNameField); fullNameField.style.display='none'; phoneField.style.display='none';
document.querySelector('.modal-close').addEventListener('click', () => { modal.classList.remove('show'); modal.setAttribute('aria-hidden','true'); });
modal.addEventListener('click', e => { if (e.target === modal) modal.classList.remove('show'); });
const memberOptions = document.createElement('div'); memberOptions.className='member-options'; memberOptions.innerHTML='<a href="#volunteer">Volunteer profile <span>↗</span></a><a href="#work">Find opportunities <span>↗</span></a><a href="#stories">My applications <span>↗</span></a><a href="#volunteer">Contact team <span>↗</span></a>'; document.querySelector('#signin-form').append(memberOptions);
document.querySelector('#signin-form').addEventListener('submit', async e => { e.preventDefault(); const status=document.querySelector('.signin-status'); const submit=e.currentTarget.querySelector('button[type="submit"]'); status.textContent='Please wait…'; submit.disabled=true; const payload=Object.fromEntries(new FormData(e.currentTarget)); const mode=modal.dataset.mode==='signup'?'signup':'login'; try { const response=await fetch('/api/auth/'+mode,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}); const data=await response.json(); if(!response.ok) throw new Error(data.message); status.textContent=data.message; setTimeout(()=>{ modal.classList.remove('show'); modal.setAttribute('aria-hidden','true'); e.currentTarget.reset(); memberOptions.classList.remove('visible'); modal.dataset.mode='login'; modal.querySelector('.modal-kicker').textContent='SOCH COMMUNITY'; modal.querySelector('h2').textContent='Welcome back.'; submit.disabled=false; },900); } catch(err) { status.textContent=err.message||'Request failed. Please try again.'; submit.disabled=false; } });
const modules=document.createElement('section'); modules.className='modules section'; modules.innerHTML='<div class="section-label">05 / MORE WAYS TO HELP</div><div class="module-grid"><a href="#volunteer"><strong>Campaigns</strong><span>Join upcoming community drives ↗</span></a><a href="#stories"><strong>Impact dashboard</strong><span>See how volunteers create change ↗</span></a><a href="#mission"><strong>Volunteer resources</strong><span>Guides, training and updates ↗</span></a></div>'; document.querySelector('#volunteer').before(modules);
const teamSection=document.createElement('section'); teamSection.className='team section'; teamSection.id='team'; teamSection.innerHTML='<details><summary>Meet the people behind the work <span>＋</span></summary><div class="team-content"><div><div class="section-label">COMMUNITY TEAM</div><h2>People who<br>show up.</h2><p>A glimpse of the SOCH Welfare Foundation team serving the Haroonabad community through awareness, welfare and volunteer initiatives.</p></div><div class="team-gallery"><img src="/team-community.jpeg" alt="SOCH Welfare Foundation community team serving together"><img src="/team-community-alt.jpeg" alt="SOCH Welfare Foundation team meeting and serving the community"></div></div></details>'; document.querySelector('#volunteer').before(teamSection);
const teamStyle=document.createElement('style'); teamStyle.textContent='.team{background:#f0eee6;padding-top:42px;padding-bottom:42px}.team details{border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.team summary{cursor:pointer;list-style:none;padding:22px 0;font-family:"Plus Jakarta Sans";font-size:20px;display:flex;justify-content:space-between}.team summary::-webkit-details-marker{display:none}.team-content{display:grid;grid-template-columns:.8fr 1.4fr;gap:7vw;align-items:start;padding:10px 0 30px}.team-content h2{font-size:clamp(38px,4vw,60px);margin:15px 0}.team-content p{color:#60766d;line-height:1.6;max-width:400px}.team-gallery{display:grid;gap:18px}.team-gallery img{width:100%;max-height:360px;object-fit:cover;border-radius:18px;filter:saturate(.8)}@media(max-width:800px){.team-content{grid-template-columns:1fr}}'; document.head.append(teamStyle);
const oldAuthForm=document.querySelector('#signin-form'); const supaAuthForm=oldAuthForm.cloneNode(true); oldAuthForm.replaceWith(supaAuthForm); supaAuthForm.addEventListener('submit',async e=>{e.preventDefault();const status=document.querySelector('.signin-status');const payload=Object.fromEntries(new FormData(supaAuthForm));const mode=modal.dataset.mode==='signup'?'signup':'login';const endpoint=mode==='signup'?`${SUPABASE_URL}/auth/v1/signup`:`${SUPABASE_URL}/auth/v1/token?grant_type=password`;const body=mode==='signup'?{email:payload.email,password:payload.password,data:{full_name:payload.fullName,phone:payload.phone}}:{email:payload.email,password:payload.password};status.textContent='Please wait…';try{const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_KEY},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.msg||data.message||'Authentication failed');status.textContent=mode==='signup'?'Account created successfully.':'You are signed in.';setTimeout(()=>{modal.classList.remove('show');modal.setAttribute('aria-hidden','true');supaAuthForm.reset();modal.dataset.mode='login'},900)}catch(err){status.textContent=err.message}});
const drawerStyle=document.createElement('style'); drawerStyle.textContent='.nav-links.open{inset:0 0 0 auto!important;width:min(380px,88vw)!important;height:100vh!important;padding:105px 34px 40px!important;background:#fffdf7!important;box-shadow:-18px 0 45px rgba(23,53,46,.22)!important;border-left:1px solid #d9ded5!important}.nav-links.open a,.nav-links.open button{font-size:17px!important}.menu.active{position:fixed;right:24px;top:20px!important}'; document.head.append(drawerStyle);
const logo = document.querySelector('.brand-mark');
logo.classList.add('blue-logo'); logo.innerHTML = '<img src="/soch-logo-clean.png" alt="SOCH Foundation logo">';
const logoStyle=document.createElement('style'); logoStyle.textContent='.brand-mark img,.mini-logo img{width:100%;height:100%;object-fit:cover;border-radius:50%;border:3px solid #d51f2d;background:transparent}.brand-mark{background:transparent!important}.mini-logo{background:transparent!important}'; document.head.append(logoStyle);
const recognition = document.createElement('section');
recognition.id = 'recognition'; recognition.className = 'recognition section';
recognition.innerHTML = `<div class="section-label">04 / GLOBAL RECOGNITION</div><div class="recognition-grid"><div><h2>Service that<br>travels <em>far.</em></h2><p>SOCH Foundation recognises volunteers whose commitment creates lasting change across education, health and environment initiatives in the Haroonabad Tehsil region of Punjab, Pakistan.</p><div class="recognition-badge"><span>✓</span><div><strong>Certificate of Global Recognition</strong><small>Celebrating exemplary community service</small></div></div></div><div class="certificate-card"><div class="mini-logo blue-logo"><img src="/soch-logo-clean.png" alt="SOCH Foundation logo"></div><strong>CERTIFICATE OF<br>GLOBAL RECOGNITION</strong><p>Presented in appreciation of exemplary commitment and meritorious service across our community programmes.</p><div class="qr-row"><a href="https://www.facebook.com/sochwelfarefoundation.hnd" target="_blank" rel="noreferrer"><img src="/qr-original.png" alt="Original certificate QR code — open SOCH Welfare Foundation Facebook"></a><a href="https://www.facebook.com/sochwelfarefoundation.hnd" target="_blank" rel="noreferrer">Scan the original certificate QR ↗</a></div></div></div>`;
document.querySelector('#volunteer').before(recognition);
form.addEventListener('submit', async (e) => {
  e.preventDefault();
  const status = document.querySelector('.form-status');
  status.textContent = 'Sending your interest…';
  try {
    const response = await fetch('/api/volunteers', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(Object.fromEntries(new FormData(form))) });
    const data = await response.json();
    status.textContent = data.message;
    if (data.ok) form.reset();
  } catch { status.textContent = 'Something went wrong. Please try again.'; }
});
const menuButton=document.querySelector('.menu'); const navLinks=document.querySelector('.nav-links'); menuButton.innerHTML='<span></span><span></span><span></span>';
const menuStyle=document.createElement('style'); menuStyle.textContent='.menu{display:flex!important;flex-direction:column;justify-content:center;gap:5px;width:42px;height:42px;padding:8px;position:relative;z-index:101}.menu span{display:block;width:26px;height:2px;background:var(--ink);margin:auto}.menu.active{font-size:0}.menu.active b{font-size:30px;font-weight:400;line-height:1}.nav-links.open{display:flex!important;position:fixed;z-index:100;inset:0;width:100vw;height:100vh;padding:115px 32px 40px;background:#fffdf7!important;box-shadow:none;flex-direction:column;align-items:stretch;gap:12px;border:0;overflow-y:auto}.nav-links.open a,.nav-links.open button{font-size:18px!important;text-align:left;padding:17px 0;border-bottom:1px solid #d9ded5;border-radius:0;background:transparent!important;color:var(--ink)!important}.nav-links.open .signin-trigger,.nav-links.open .signup-trigger{padding:17px 18px;border:1px solid #c7d3cb;border-radius:16px;background:#edf4ee!important;text-align:center;margin-top:4px}.nav-links.open .signup-trigger{background:var(--green)!important;border-color:var(--green)}.nav-links.open .nav-cta{background:var(--orange)!important;color:white!important;border:0;padding:17px 20px;border-radius:99px;text-align:center;margin-top:10px}'; document.head.append(menuStyle);
menuButton.setAttribute('aria-expanded','false');
menuButton.addEventListener('click', () => { const isOpen=navLinks.classList.toggle('open'); modal.classList.remove('show'); menuButton.classList.toggle('active',isOpen); menuButton.setAttribute('aria-expanded',String(isOpen)); menuButton.innerHTML=isOpen?'<b>×</b>':'<span></span><span></span><span></span>'; });
navLinks.addEventListener('click', e => { if(e.target.closest('a') || e.target.closest('button')) { navLinks.classList.remove('open'); menuButton.classList.remove('active'); menuButton.setAttribute('aria-expanded','false'); menuButton.innerHTML='<span></span><span></span><span></span>'; } });

// Supabase volunteer submissions
const oldVolunteerForm=document.querySelector('#volunteer-form');
if(oldVolunteerForm){const supaVolunteerForm=oldVolunteerForm.cloneNode(true); oldVolunteerForm.replaceWith(supaVolunteerForm); supaVolunteerForm.addEventListener('submit',async e=>{e.preventDefault(); const status=supaVolunteerForm.querySelector('.form-status'); status.textContent='Sending your interest�'; const payload=Object.fromEntries(new FormData(supaVolunteerForm)); try{const res=await fetch(`${SUPABASE_URL}/rest/v1/volunteers`,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_KEY,Prefer:'return=minimal'},body:JSON.stringify(payload)}); if(!res.ok) throw new Error('Could not submit right now.'); status.textContent='Thank you � your interest was received.'; supaVolunteerForm.reset();}catch(err){status.textContent=err.message;}});}
